{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "my-stack.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "my-stack.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- if .Values.ingress.className }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className | quote }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if and .Values.ingress.tls.enabled .Values.ingress.host }}
  tls:
    - hosts: [{{ .Values.ingress.host | quote }}]
      secretName: {{ .Values.ingress.tls.secretName | quote }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.frontendPath }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "frontend.fullname" (dict "Chart" (index .Subcharts "frontend").Chart "Release" .Release "Values" (index .Values "frontend") ) }}
                port:
                  number: {{ .Values.frontend.service.port }}
          - path: {{ .Values.ingress.backendPath }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "backend.fullname" (dict "Chart" (index .Subcharts "backend").Chart "Release" .Release "Values" (index .Values "backend") ) }}
                port:
                  number: {{ .Values.backend.service.port }}
{{- end }}

