apiVersion: v2
name: my-stack
description: Umbrella chart for Frontend + Backend
type: application
version: 0.1.0
dependencies:
  - name: frontend
    version: 0.1.0
    repository: "file://./charts/frontend"
  - name: backend
    version: 0.1.0
    repository: "file://./charts/backend"
