apiVersion: v2
name: my-stack
description: Umbrella chart for deploying frontend + backend together
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: frontend
    version: 0.1.0
    repository: "file://./charts/frontend"
  - name: backend
    version: 0.1.0
    repository: "file://./charts/backend"
