apiVersion: v2
name: my-full-stack-app
description: A Helm umbrella chart for full-stack application with React frontend and Node.js backend
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: frontend
    version: 1.0.0
    condition: frontend.enabled
  - name: backend
    version: 1.0.0
    condition: backend.enabled

maintainers:
  - name: TarkeshHD
    email: your-email@example.com
