global:
  appName: my-stack
  imagePullSecrets: []   # e.g., ["regcred"]

ingress:
  enabled: true
  className: nginx           # set to your ingress class (e.g., nginx)
  host: my-stack.127.0.0.1.nip.io   # dev-friendly host; change for prod
  tls:
    enabled: false
    secretName: ""           # e.g., "my-stack-tls"
  frontendPath: /
  backendPath: /api

frontend:
  image:
    repository: ghcr.io/tarkeshhd/my-amplify-app
    tag: latest
    pullPolicy: IfNotPresent
  replicaCount: 2
  service:
    type: ClusterIP
    port: 80
  containerPort: 80
  resources:
    requests: { cpu: "100m", memory: "128Mi" }
    limits:   { cpu: "500m", memory: "256Mi" }
  env: []
  serviceAccount:
    create: false
    automount: false
    annotations: {}
    imagePullSecrets: []

backend:
  image:
    repository: ghcr.io/tarkeshhd/backend-automation
    tag: latest
    pullPolicy: IfNotPresent
  replicaCount: 2
  service:
    type: ClusterIP
    port: 8080
  containerPort: 8080
  resources:
    requests: { cpu: "100m", memory: "128Mi" }
    limits:   { cpu: "1", memory: "512Mi" }
  env:
    - name: NODE_ENV
      value: "production"
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70
    # targetMemoryUtilizationPercentage: 75
