global:
  appName: my-stack
  imagePullSecrets: []   # e.g., ["regcred"]

ingress:
  enabled: true
  className: nginx
  host: my-stack.127.0.0.1.nip.io
  tls:
    enabled: false
    secretName: ""
  frontendPath: /
  backendPath: /api

frontend:
  image:
    repository: ghcr.io/tarkeshhd/my-amplify-app
    tag: latest
    pullPolicy: IfNotPresent
  replicaCount: 2
  service:
    type: ClusterIP
    port: 80
  containerPort: 80
  resources:
    requests: { cpu: "100m", memory: "128Mi" }
    limits:   { cpu: "500m", memory: "256Mi" }
  env: []
  config:
    enabled: false
    data: {}
    files: {}
  serviceAccount:
    create: false
    automount: false
    annotations: {}
    imagePullSecrets: []
  autoscaling:
    enabled: false
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70

backend:
  image:
    repository: ghcr.io/tarkeshhd/backend-automation
    tag: latest
    pullPolicy: IfNotPresent
  replicaCount: 2
  service:
    type: ClusterIP
    port: 3000          # CHANGE if your app listens on a different port
  containerPort: 3000   # CHANGE if your app listens on a different port
  resources:
    requests: { cpu: "100m", memory: "128Mi" }
    limits:   { cpu: "1", memory: "512Mi" }
  env:
    - name: NODE_ENV
      value: "production"
    - name: PORT
      value: "3000"     # keep in sync with containerPort/service.port
  config:
    enabled: false
    data: {}
    files: {}
  secrets:
    enabled: false
    nameOverride: ""
    data: {}            # e.g., MONGODB_URI: "mongodb://..."
  autoscaling:
    enabled: false
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70
    # targetMemoryUtilizationPercentage: 75
