replicaCount: 1
image:
  repository: backend
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080
containerPort: 8080
resources: {}
env: []
autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
  # targetMemoryUtilizationPercentage: 75
