replicaCount: 1
image:
  repository: backend
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080
containerPort: 8080
resources: {}
env: []

# NEW: ConfigMap settings
config:
  enabled: true
  data: {}   # e.g., { LOG_LEVEL: "info", FEATURE_X: "true" }
  files: {}  # e.g., { appsettings.json: |-
             #         { "port": 8080, "featureX": true } }

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
  # targetMemoryUtilizationPercentage: 75
