{{- if or .Values.secrets.enabled .Values.database.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}-secret
  labels:
    {{- include "backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.database.password }}
  database-password: {{ .Values.database.password | quote }}
  {{- end }}
  {{- with .Values.secrets.data }}
  {{- range $key, $value := . }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
{{- end }}
