apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend.fullname" . }}
  labels: {{- include "backend.labels" . | nindent 4 }}
spec:
  type: {{ $.Values.backend.service.type }}
  selector: {{- include "backend.labels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ $.Values.backend.service.port }}
      targetPort: {{ $.Values.backend.containerPort }}
